apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: raushni
$patch: delete
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: raushni
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: raushni
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: raushni
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: document-generator
  namespace: raushni
$patch: delete

