apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: raushni-public
  namespace: raushni
spec:
  tls:
    - hosts:
        - raushni-dev.com
        - www.raushni-dev.com
        - api.raushni-dev.com
        - cms.raushni-dev.com
      secretName: raushni-dev-tls
  rules:
    - host: raushni-dev.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  name: http
          - path: /uploads
            pathType: Prefix
            backend:
              service:
                name: strapi
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http
    - host: www.raushni-dev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http
    - host: api.raushni-dev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  name: http
    - host: cms.raushni-dev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strapi
                port:
                  name: http

