apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespace.yaml
  - ../../serviceaccount.yaml
  - ../../configmap.yaml
  - ../../secrets.yaml
  - ../../postgres-deployment.yaml
  - ../../redis-deployment.yaml
  - ../../backend-deployment.yaml
  - ../../frontend-deployment.yaml
  - ../../strapi-deployment.yaml
  - ../../ingress.yaml
  - ../../network-policy.yaml

patches:
  - path: configmap-nonprod.yaml
  - path: ingress-nonprod.yaml
  - path: external-secret-nonprod.yaml
  - path: replicas-nonprod.yaml

