apiVersion: v1
kind: ServiceAccount
metadata:
  name: raushni-app
  namespace: raushni
  labels:
    app.kubernetes.io/name: raushni-app
    app.kubernetes.io/part-of: raushni-platform
automountServiceAccountToken: false
