apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: raushni-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/raushni-production-external-secrets
