apiVersion: v1
kind: ConfigMap
metadata:
  name: raushni-config
  namespace: raushni
data:
  API_PUBLIC_URL: https://api.raushni-dev.com
  APP_PUBLIC_URL: https://raushni-dev.com
  CMS_CORS_ORIGINS: https://raushni-dev.com,https://www.raushni-dev.com,https://api.raushni-dev.com,https://cms.raushni-dev.com
  CMS_PUBLIC_URL: https://cms.raushni-dev.com
  DD_ENV: development
  ENVIRONMENT: development
  NEXT_PUBLIC_API_URL: https://api.raushni-dev.com
  NEXT_PUBLIC_CMS_URL: https://cms.raushni-dev.com
  NEXTAUTH_URL: https://raushni-dev.com
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=development,service.namespace=raushni
  STRAPI_NODE_ENV: production
