apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: raushni-secrets
  namespace: raushni
spec:
  data:
    - remoteRef:
        key: /raushni/development/app
        property: POSTGRES_USER
      secretKey: POSTGRES_USER
    - remoteRef:
        key: /raushni/development/app
        property: POSTGRES_PASSWORD
      secretKey: POSTGRES_PASSWORD
    - remoteRef:
        key: /raushni/development/app
        property: BACKEND_DATABASE_URL
      secretKey: BACKEND_DATABASE_URL
    - remoteRef:
        key: /raushni/development/app
        property: CMS_DATABASE_NAME
      secretKey: CMS_DATABASE_NAME
    - remoteRef:
        key: /raushni/development/app
        property: CMS_DATABASE_USERNAME
      secretKey: CMS_DATABASE_USERNAME
    - remoteRef:
        key: /raushni/development/app
        property: CMS_DATABASE_PASSWORD
      secretKey: CMS_DATABASE_PASSWORD
    - remoteRef:
        key: /raushni/development/app
        property: REDIS_PASSWORD
      secretKey: REDIS_PASSWORD
    - remoteRef:
        key: /raushni/development/app
        property: REDIS_URL
      secretKey: REDIS_URL
    - remoteRef:
        key: /raushni/development/app
        property: NEXTAUTH_SECRET
      secretKey: NEXTAUTH_SECRET
    - remoteRef:
        key: /raushni/development/app
        property: NEXTAUTH_ADMIN_EMAIL
      secretKey: NEXTAUTH_ADMIN_EMAIL
    - remoteRef:
        key: /raushni/development/app
        property: NEXTAUTH_ADMIN_PASSWORD
      secretKey: NEXTAUTH_ADMIN_PASSWORD
    - remoteRef:
        key: /raushni/development/app
        property: NEXTAUTH_STAFF_EMAIL
      secretKey: NEXTAUTH_STAFF_EMAIL
    - remoteRef:
        key: /raushni/development/app
        property: NEXTAUTH_STAFF_PASSWORD
      secretKey: NEXTAUTH_STAFF_PASSWORD
    - remoteRef:
        key: /raushni/development/app
        property: INTERNAL_API_KEY
      secretKey: INTERNAL_API_KEY
    - remoteRef:
        key: /raushni/development/app
        property: CMS_API_TOKEN
      secretKey: CMS_API_TOKEN
    - remoteRef:
        key: /raushni/development/app
        property: STRIPE_SECRET_KEY
      secretKey: STRIPE_SECRET_KEY
    - remoteRef:
        key: /raushni/development/app
        property: STRIPE_PUBLISHABLE_KEY
      secretKey: STRIPE_PUBLISHABLE_KEY
    - remoteRef:
        key: /raushni/development/app
        property: STRIPE_WEBHOOK_SECRET
      secretKey: STRIPE_WEBHOOK_SECRET
    - remoteRef:
        key: /raushni/development/app
        property: STRAPI_APP_KEYS
      secretKey: STRAPI_APP_KEYS
    - remoteRef:
        key: /raushni/development/app
        property: STRAPI_API_TOKEN_SALT
      secretKey: STRAPI_API_TOKEN_SALT
    - remoteRef:
        key: /raushni/development/app
        property: STRAPI_ADMIN_JWT_SECRET
      secretKey: STRAPI_ADMIN_JWT_SECRET
    - remoteRef:
        key: /raushni/development/app
        property: STRAPI_JWT_SECRET
      secretKey: STRAPI_JWT_SECRET
    - remoteRef:
        key: /raushni/development/app
        property: STRAPI_TRANSFER_TOKEN_SALT
      secretKey: STRAPI_TRANSFER_TOKEN_SALT
    - remoteRef:
        key: /raushni/development/app
        property: DD_API_KEY
      secretKey: DD_API_KEY
