FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache vips-dev python3 make g++ gcc curl
COPY package*.json ./
RUN npm install --no-optional --legacy-peer-deps
COPY . .
RUN mkdir -p public/uploads
EXPOSE 1337
CMD ["npm", "start"]
